// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metrics.proto

package io_prometheus_client // import "github.com/prometheus/client_model/go"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MetricType int32

const (
	MetricType_COUNTER   MetricType = 0
	MetricType_GAUGE     MetricType = 1
	MetricType_SUMMARY   MetricType = 2
	MetricType_UNTYPED   MetricType = 3
	MetricType_HISTOGRAM MetricType = 4
)

var MetricType_name = map[int32]string{
	0: "COUNTER",
	1: "GAUGE",
	2: "SUMMARY",
	3: "UNTYPED",
	4: "HISTOGRAM",
}
var MetricType_value = map[string]int32{
	"COUNTER":   0,
	"GAUGE":     1,
	"SUMMARY":   2,
	"UNTYPED":   3,
	"HISTOGRAM": 4,
}

func (x MetricType) Enum() *MetricType {
	p := new(MetricType)
	*p = x
	return p
}
func (x MetricType) String() string {
	return proto.EnumName(MetricType_name, int32(x))
}
func (x *MetricType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MetricType_value, data, "MetricType")
	if err != nil {
		return err
	}
	*x = MetricType(value)
	return nil
}
func (MetricType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_metrics_967ed95007e86b2f, []int{0}
}

type LabelPair struct {
	Name                 *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value                *string  `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LabelPair) Reset()         { *m = LabelPair{} }
func (m *LabelPair) String() string { return proto.CompactTextString(m) }
func (*LabelPair) ProtoMessage()    {}
func (*LabelPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_metrics_967ed95007e86b2f, []int{0}
}
func (m *LabelPair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LabelPair.Unmarshal(m, b)
}
func (m *LabelPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LabelPair.Marshal(b, m, deterministic)
}
func (dst *LabelPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LabelPair.Merge(dst, src)
}
func (m *LabelPair) XXX_Size() int {
	return xxx_messageInfo_LabelPair.Size(m)
}
func (m *LabelPair) XXX_DiscardUnknown() {
	xxx_messageInfo_LabelPair.DiscardUnknown(m)
}

var xxx_messageInfo_LabelPair proto.InternalMessageInfo

func (m *LabelPair) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *LabelPair) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type Gauge struct {
	Value                *float64 `protobuf:"fixed64,1,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Gauge) Reset()         { *m = Gauge{} }
func (m *Gauge) String() string { return proto.CompactTextString(m) }
func (*Gauge) ProtoMessage()    {}
func (*Gauge) Descriptor() ([]byte, []int) {
	return fileDescriptor_metrics_967ed95007e86b2f, []int{1}
}
func (m *Gauge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Gauge.Unmarshal(m, b)
}
func (m *Gauge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Gauge.Marshal(b, m, deterministic)
}
func (dst *Gauge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gauge.Merge(dst, src)
}
func (m *Gauge) XXX_Size() int {
	return xxx_messageInfo_Gauge.Size(m)
}
func (m *Gauge) XXX_DiscardUnknown() {
	xxx_messageInfo_Gauge.DiscardUnknown(m)
}

var xxx_messageInfo_Gauge proto.InternalMessageInfo

func (m *Gauge) GetValue() float64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

type Counter struct {
	Value                *float64 `protobuf:"fixed64,1,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Counter) Reset()         { *m = Counter{} }
func (m *Counter) String() string { return proto.CompactTextString(m) }
func (*Counter) ProtoMessage()    {}
func (*Counter) Descriptor() ([]byte, []int) {
	return fileDescriptor_metrics_967ed95007e86b2f, []int{2}
}
func (m *Counter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Counter.Unmarshal(m, b)
}
func (m *Counter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Counter.Marshal(b, m, deterministic)
}
func (dst *Counter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Counter.Merge(dst, src)
}
func (m *Counter) XXX_Size() int {
	return xxx_messageInfo_Counter.Size(m)
}
func (m *Counter) XXX_DiscardUnknown() {
	xxx_messageInfo_Counter.DiscardUnknown(m)
}

var xxx_messageInfo_Counter proto.InternalMessageInfo

func (m *Counter) GetValue() float64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

type Quantile struct {
	Quantile             *float64 `protobuf:"fixed64,1,opt,name=quantile" json:"quantile,omitempty"`
	Value                *float64 `protobuf:"fixed64,2,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Quantile) Reset()         { *m = Quantile{} }
func (m *Quantile) String() string { return proto.CompactTextString(m) }
func (*Quantile) ProtoMessage()    {}
func (*Quantile) Descriptor() ([]byte, []int) {
	return fileDescriptor_metrics_967ed95007e86b2f, []int{3}
}
func (m *Quantile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Quantile.Unmarshal(m, b)
}
func (m *Quantile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Quantile.Marshal(b, m, deterministic)
}
func (dst *Quantile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Quantile.Merge(dst, src)
}
func (m *Quantile) XXX_Size() int {
	return xxx_messageInfo_Quantile.Size(m)
}
func (m *Quantile) XXX_DiscardUnknown() {
	xxx_messageInfo_Quantile.DiscardUnknown(m)
}

var xxx_messageInfo_Quantile proto.InternalMessageInfo

func (m *Quantile) GetQuantile() float64 {
	if m != nil && m.Quantile != nil {
		return *m.Quantile
	}
	return 0
}

func (m *Quantile) GetValue() float64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

type Summary struct {
	SampleCount          *uint64     `protobuf:"varint,1,opt,name=sample_count,json=sampleCount" json:"sample_count,omitempty"`
	SampleSum            *float64    `protobuf:"fixed64,2,opt,name=sample_sum,json=sampleSum" json:"sample_sum,omitempty"`
	Quantile             []*Quantile `protobuf:"bytes,3,rep,name=quantile" json:"quantile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Summary) Reset()         { *m = Summary{} }
func (m *Summary) String() string { return proto.CompactTextString(m) }
func (*Summary) ProtoMessage()    {}
func (*Summary) Descriptor() ([]byte, []int) {
	return fileDescriptor_metrics_967ed95007e86b2f, []int{4}
}
func (m *Summary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Summary.Unmarshal(m, b)
}
func (m *Summary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Summary.Marshal(b, m, deterministic)
}
func (dst *Summary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Summary.Merge(dst, src)
}
func (m *Summary) XXX_Size() int {
	return xxx_messageInfo_Summary.Size(m)
}
func (m *Summary) XXX_DiscardUnknown() {
	xxx_messageInfo_Summary.DiscardUnknown(m)
}

var xxx_messageInfo_Summary proto.InternalMessageInfo

func (m *Summary) GetSampleCount() uint64 {
	if m != nil && m.SampleCount != nil {
		return *m.SampleCount
	}
	return 0
}

func (m *Summary) GetSampleSum() float64 {
	if m != nil && m.SampleSum != nil {
		return *m.SampleSum
	}
	return 0
}

func (m *Summary) GetQuantile() []*Quantile {
	if m != nil {
		return m.Quantile
	}
	return nil
}

type Untyped struct {
	Value                *float64 `protobuf:"fixed64,1,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Untyped) Reset()         { *m = Untyped{} }
func (m *Untyped) String() string { return proto.CompactTextString(m) }
func (*Untyped) ProtoMessage()    {}
func (*Untyped) Descriptor() ([]byte, []int) {
	return fileDescriptor_metrics_967ed95007e86b2f, []int{5}
}
func (m *Untyped) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Untyped.Unmarshal(m, b)
}
func (m *Untyped) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Untyped.Marshal(b, m, deterministic)
}
func (dst *Untyped) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Untyped.Merge(dst, src)
}
func (m *Untyped) XXX_Size() int {
	return xxx_messageInfo_Untyped.Size(m)
}
func (m *Untyped) XXX_DiscardUnknown() {
	xxx_messageInfo_Untyped.DiscardUnknown(m)
}

var xxx_messageInfo_Untyped proto.InternalMessageInfo

func (m *Untyped) GetValue() float64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

type Histogram struct {
	SampleCount          *uint64           `protobuf:"varint,1,opt,name=sample_count,json=sampleCount" json:"sample_count,omitempty"`
	SampleSum            *float64          `protobuf:"fixed64,2,opt,name=sample_sum,json=sampleSum" json:"sample_sum,omitempty"`
	Bucket               []*Bucket         `protobuf:"bytes,3,rep,name=bucket" json:"bucket,omitempty"`
	Exemplars            map[string]string `protobuf:"bytes,4,rep,name=exemplars" json:"exemplars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Histogram) Reset()         { *m = Histogram{} }
func (m *Histogram) String() string { return proto.CompactTextString(m) }
func (*Histogram) ProtoMessage()    {}
func (*Histogram) Descriptor() ([]byte, []int) {
	return fileDescriptor_metrics_967ed95007e86b2f, []int{6}
}
func (m *Histogram) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Histogram.Unmarshal(m, b)
}
func (m *Histogram) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Histogram.Marshal(b, m, deterministic)
}
func (dst *Histogram) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Histogram.Merge(dst, src)
}
func (m *Histogram) XXX_Size() int {
	return xxx_messageInfo_Histogram.Size(m)
}
func (m *Histogram) XXX_DiscardUnknown() {
	xxx_messageInfo_Histogram.DiscardUnknown(m)
}

var xxx_messageInfo_Histogram proto.InternalMessageInfo

func (m *Histogram) GetSampleCount() uint64 {
	if m != nil && m.SampleCount != nil {
		return *m.SampleCount
	}
	return 0
}

func (m *Histogram) GetSampleSum() float64 {
	if m != nil && m.SampleSum != nil {
		return *m.SampleSum
	}
	return 0
}

func (m *Histogram) GetBucket() []*Bucket {
	if m != nil {
		return m.Bucket
	}
	return nil
}

func (m *Histogram) GetExemplars() map[string]string {
	if m != nil {
		return m.Exemplars
	}
	return nil
}

type Bucket struct {
	CumulativeCount      *uint64           `protobuf:"varint,1,opt,name=cumulative_count,json=cumulativeCount" json:"cumulative_count,omitempty"`
	UpperBound           *float64          `protobuf:"fixed64,2,opt,name=upper_bound,json=upperBound" json:"upper_bound,omitempty"`
	Exemplars            map[string]string `protobuf:"bytes,3,rep,name=exemplars" json:"exemplars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Bucket) Reset()         { *m = Bucket{} }
func (m *Bucket) String() string { return proto.CompactTextString(m) }
func (*Bucket) ProtoMessage()    {}
func (*Bucket) Descriptor() ([]byte, []int) {
	return fileDescriptor_metrics_967ed95007e86b2f, []int{7}
}
func (m *Bucket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bucket.Unmarshal(m, b)
}
func (m *Bucket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bucket.Marshal(b, m, deterministic)
}
func (dst *Bucket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bucket.Merge(dst, src)
}
func (m *Bucket) XXX_Size() int {
	return xxx_messageInfo_Bucket.Size(m)
}
func (m *Bucket) XXX_DiscardUnknown() {
	xxx_messageInfo_Bucket.DiscardUnknown(m)
}

var xxx_messageInfo_Bucket proto.InternalMessageInfo

func (m *Bucket) GetCumulativeCount() uint64 {
	if m != nil && m.CumulativeCount != nil {
		return *m.CumulativeCount
	}
	return 0
}

func (m *Bucket) GetUpperBound() float64 {
	if m != nil && m.UpperBound != nil {
		return *m.UpperBound
	}
	return 0
}

func (m *Bucket) GetExemplars() map[string]string {
	if m != nil {
		return m.Exemplars
	}
	return nil
}

type Metric struct {
	Label                []*LabelPair      `protobuf:"bytes,1,rep,name=label" json:"label,omitempty"`
	Gauge                *Gauge            `protobuf:"bytes,2,opt,name=gauge" json:"gauge,omitempty"`
	Counter              *Counter          `protobuf:"bytes,3,opt,name=counter" json:"counter,omitempty"`
	Summary              *Summary          `protobuf:"bytes,4,opt,name=summary" json:"summary,omitempty"`
	Untyped              *Untyped          `protobuf:"bytes,5,opt,name=untyped" json:"untyped,omitempty"`
	Histogram            *Histogram        `protobuf:"bytes,7,opt,name=histogram" json:"histogram,omitempty"`
	TimestampMs          *int64            `protobuf:"varint,6,opt,name=timestamp_ms,json=timestampMs" json:"timestamp_ms,omitempty"`
	Exemplars            map[string]string `protobuf:"bytes,8,rep,name=exemplars" json:"exemplars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Metric) Reset()         { *m = Metric{} }
func (m *Metric) String() string { return proto.CompactTextString(m) }
func (*Metric) ProtoMessage()    {}
func (*Metric) Descriptor() ([]byte, []int) {
	return fileDescriptor_metrics_967ed95007e86b2f, []int{8}
}
func (m *Metric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metric.Unmarshal(m, b)
}
func (m *Metric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metric.Marshal(b, m, deterministic)
}
func (dst *Metric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metric.Merge(dst, src)
}
func (m *Metric) XXX_Size() int {
	return xxx_messageInfo_Metric.Size(m)
}
func (m *Metric) XXX_DiscardUnknown() {
	xxx_messageInfo_Metric.DiscardUnknown(m)
}

var xxx_messageInfo_Metric proto.InternalMessageInfo

func (m *Metric) GetLabel() []*LabelPair {
	if m != nil {
		return m.Label
	}
	return nil
}

func (m *Metric) GetGauge() *Gauge {
	if m != nil {
		return m.Gauge
	}
	return nil
}

func (m *Metric) GetCounter() *Counter {
	if m != nil {
		return m.Counter
	}
	return nil
}

func (m *Metric) GetSummary() *Summary {
	if m != nil {
		return m.Summary
	}
	return nil
}

func (m *Metric) GetUntyped() *Untyped {
	if m != nil {
		return m.Untyped
	}
	return nil
}

func (m *Metric) GetHistogram() *Histogram {
	if m != nil {
		return m.Histogram
	}
	return nil
}

func (m *Metric) GetTimestampMs() int64 {
	if m != nil && m.TimestampMs != nil {
		return *m.TimestampMs
	}
	return 0
}

func (m *Metric) GetExemplars() map[string]string {
	if m != nil {
		return m.Exemplars
	}
	return nil
}

type MetricFamily struct {
	Name                 *string     `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Help                 *string     `protobuf:"bytes,2,opt,name=help" json:"help,omitempty"`
	Type                 *MetricType `protobuf:"varint,3,opt,name=type,enum=io.prometheus.client.MetricType" json:"type,omitempty"`
	Metric               []*Metric   `protobuf:"bytes,4,rep,name=metric" json:"metric,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MetricFamily) Reset()         { *m = MetricFamily{} }
func (m *MetricFamily) String() string { return proto.CompactTextString(m) }
func (*MetricFamily) ProtoMessage()    {}
func (*MetricFamily) Descriptor() ([]byte, []int) {
	return fileDescriptor_metrics_967ed95007e86b2f, []int{9}
}
func (m *MetricFamily) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricFamily.Unmarshal(m, b)
}
func (m *MetricFamily) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricFamily.Marshal(b, m, deterministic)
}
func (dst *MetricFamily) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricFamily.Merge(dst, src)
}
func (m *MetricFamily) XXX_Size() int {
	return xxx_messageInfo_MetricFamily.Size(m)
}
func (m *MetricFamily) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricFamily.DiscardUnknown(m)
}

var xxx_messageInfo_MetricFamily proto.InternalMessageInfo

func (m *MetricFamily) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *MetricFamily) GetHelp() string {
	if m != nil && m.Help != nil {
		return *m.Help
	}
	return ""
}

func (m *MetricFamily) GetType() MetricType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return MetricType_COUNTER
}

func (m *MetricFamily) GetMetric() []*Metric {
	if m != nil {
		return m.Metric
	}
	return nil
}

func init() {
	proto.RegisterType((*LabelPair)(nil), "io.prometheus.client.LabelPair")
	proto.RegisterType((*Gauge)(nil), "io.prometheus.client.Gauge")
	proto.RegisterType((*Counter)(nil), "io.prometheus.client.Counter")
	proto.RegisterType((*Quantile)(nil), "io.prometheus.client.Quantile")
	proto.RegisterType((*Summary)(nil), "io.prometheus.client.Summary")
	proto.RegisterType((*Untyped)(nil), "io.prometheus.client.Untyped")
	proto.RegisterType((*Histogram)(nil), "io.prometheus.client.Histogram")
	proto.RegisterMapType((map[string]string)(nil), "io.prometheus.client.Histogram.ExemplarsEntry")
	proto.RegisterType((*Bucket)(nil), "io.prometheus.client.Bucket")
	proto.RegisterMapType((map[string]string)(nil), "io.prometheus.client.Bucket.ExemplarsEntry")
	proto.RegisterType((*Metric)(nil), "io.prometheus.client.Metric")
	proto.RegisterMapType((map[string]string)(nil), "io.prometheus.client.Metric.ExemplarsEntry")
	proto.RegisterType((*MetricFamily)(nil), "io.prometheus.client.MetricFamily")
	proto.RegisterEnum("io.prometheus.client.MetricType", MetricType_name, MetricType_value)
}

func init() { proto.RegisterFile("metrics.proto", fileDescriptor_metrics_967ed95007e86b2f) }

var fileDescriptor_metrics_967ed95007e86b2f = []byte{
	// 667 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xcd, 0x4e, 0xdb, 0x4a,
	0x14, 0xbe, 0x4e, 0x9c, 0x04, 0x9f, 0x00, 0xd7, 0x1a, 0xb1, 0xb0, 0xb8, 0x70, 0x93, 0xcb, 0x8a,
	0xdb, 0x4a, 0x46, 0x45, 0xa0, 0x56, 0x94, 0x2e, 0x80, 0xa6, 0x01, 0x89, 0x00, 0x9d, 0x24, 0x0b,
	0xba, 0x89, 0x1c, 0x33, 0x4a, 0x2c, 0x3c, 0xb6, 0x6b, 0xcf, 0xa0, 0xe6, 0x09, 0xda, 0x5d, 0xdf,
	0xa1, 0xef, 0xd5, 0x77, 0xa9, 0xe6, 0xc7, 0x31, 0x91, 0x4c, 0xba, 0x29, 0xbb, 0x99, 0x73, 0xbe,
	0xef, 0xcc, 0x37, 0xc7, 0xe7, 0x1b, 0xc3, 0x1a, 0x25, 0x2c, 0x0d, 0xfc, 0xcc, 0x4d, 0xd2, 0x98,
	0xc5, 0x68, 0x23, 0x88, 0xc5, 0x8a, 0x12, 0x36, 0x25, 0x3c, 0x73, 0xfd, 0x30, 0x20, 0x11, 0xdb,
	0x39, 0x04, 0xeb, 0xd2, 0x1b, 0x93, 0xf0, 0xc6, 0x0b, 0x52, 0x84, 0xc0, 0x8c, 0x3c, 0x4a, 0x1c,
	0xa3, 0x6d, 0xec, 0x5a, 0x58, 0xae, 0xd1, 0x06, 0xd4, 0x1e, 0xbc, 0x90, 0x13, 0xa7, 0x22, 0x83,
	0x6a, 0xb3, 0xb3, 0x0d, 0xb5, 0xae, 0xc7, 0x27, 0x8f, 0xd2, 0x82, 0x63, 0xe4, 0xe9, 0x16, 0x34,
	0xce, 0x62, 0x1e, 0x31, 0x92, 0x3e, 0x01, 0x38, 0x86, 0x95, 0x8f, 0xdc, 0x8b, 0x58, 0x10, 0x12,
	0xb4, 0x09, 0x2b, 0x9f, 0xf5, 0x5a, 0x83, 0xe6, 0xfb, 0xc5, 0xd3, 0xe7, 0xec, 0xaf, 0x06, 0x34,
	0xfa, 0x9c, 0x52, 0x2f, 0x9d, 0xa1, 0xff, 0x60, 0x35, 0xf3, 0x68, 0x12, 0x92, 0x91, 0x2f, 0x4e,
	0x94, 0x15, 0x4c, 0xdc, 0x54, 0x31, 0x29, 0x02, 0x6d, 0x03, 0x68, 0x48, 0xc6, 0xa9, 0xae, 0x64,
	0xa9, 0x48, 0x9f, 0x53, 0x74, 0xf4, 0xe8, 0xfc, 0x6a, 0xbb, 0xba, 0xdb, 0xdc, 0xff, 0xd7, 0x2d,
	0xeb, 0x95, 0x9b, 0x2b, 0x2e, 0xf4, 0x89, 0x8b, 0x0e, 0x23, 0x36, 0x4b, 0xc8, 0xdd, 0x13, 0x17,
	0xfd, 0x5e, 0x01, 0xeb, 0x3c, 0xc8, 0x58, 0x3c, 0x49, 0x3d, 0xfa, 0x07, 0xc4, 0x1e, 0x40, 0x7d,
	0xcc, 0xfd, 0x7b, 0xc2, 0xb4, 0xd4, 0xad, 0x72, 0xa9, 0xa7, 0x12, 0x83, 0x35, 0x16, 0x5d, 0x82,
	0x45, 0xbe, 0x10, 0x9a, 0x84, 0x5e, 0x9a, 0x39, 0xa6, 0x24, 0xba, 0xe5, 0xc4, 0xb9, 0x56, 0xb7,
	0x93, 0x13, 0x3a, 0x11, 0x4b, 0x67, 0xb8, 0x28, 0xb0, 0x79, 0x0c, 0xeb, 0x8b, 0x49, 0x64, 0x43,
	0xf5, 0x9e, 0xcc, 0xf4, 0xdc, 0x88, 0x65, 0xf9, 0xd8, 0x1c, 0x55, 0xde, 0x18, 0x3b, 0x3f, 0x0d,
	0xa8, 0x2b, 0x79, 0xe8, 0x7f, 0xb0, 0x7d, 0x4e, 0x79, 0xe8, 0xb1, 0xe0, 0x61, 0xb1, 0x25, 0x7f,
	0x17, 0x71, 0xd5, 0x96, 0x16, 0x34, 0x79, 0x92, 0x90, 0x74, 0x34, 0x8e, 0x79, 0x74, 0xa7, 0xfb,
	0x02, 0x32, 0x74, 0x2a, 0x22, 0xe8, 0xe2, 0xf1, 0x15, 0x55, 0x6f, 0x5e, 0x2e, 0xeb, 0xcd, 0xb3,
	0xdd, 0xef, 0x9b, 0x09, 0xf5, 0x9e, 0x74, 0x1e, 0x3a, 0x84, 0x5a, 0x28, 0xcc, 0xe5, 0x18, 0x52,
	0x4f, 0xab, 0x5c, 0xcf, 0xdc, 0x7f, 0x58, 0xa1, 0xd1, 0x2b, 0xa8, 0x4d, 0x84, 0xb9, 0x64, 0xed,
	0xe6, 0xfe, 0x3f, 0xe5, 0x34, 0xe9, 0x3f, 0xac, 0x90, 0xe8, 0x35, 0x34, 0x7c, 0x65, 0x38, 0xa7,
	0x2a, 0x49, 0xdb, 0xe5, 0x24, 0xed, 0x4a, 0x9c, 0xa3, 0x05, 0x31, 0x53, 0x4e, 0x72, 0xcc, 0x65,
	0x44, 0x6d, 0x37, 0x9c, 0xa3, 0x05, 0x91, 0xab, 0xc9, 0x77, 0x6a, 0xcb, 0x88, 0xda, 0x1e, 0x38,
	0x47, 0xa3, 0x77, 0x60, 0x4d, 0xf3, 0x21, 0x73, 0x1a, 0x92, 0xda, 0xfa, 0xcd, 0x2c, 0xe2, 0x82,
	0x21, 0x2c, 0xc4, 0x02, 0x4a, 0x32, 0xe6, 0xd1, 0x64, 0x44, 0x33, 0xa7, 0xde, 0x36, 0x76, 0xab,
	0xb8, 0x39, 0x8f, 0xf5, 0xb2, 0xc5, 0x51, 0x58, 0x59, 0x36, 0x0a, 0xea, 0x3b, 0x3d, 0xdb, 0x28,
	0xfc, 0x30, 0x60, 0x55, 0x1d, 0xf1, 0xc1, 0xa3, 0x41, 0x38, 0x2b, 0x7d, 0x60, 0x11, 0x98, 0x53,
	0x12, 0x26, 0x9a, 0x2d, 0xd7, 0xe8, 0x00, 0x4c, 0xd1, 0x2c, 0xf9, 0x2d, 0xd7, 0xf7, 0xdb, 0xcb,
	0xc4, 0x0f, 0x66, 0x09, 0xc1, 0x12, 0x2d, 0xde, 0x06, 0xf5, 0xe4, 0x6b, 0x8b, 0x6f, 0x2d, 0xe3,
	0x61, 0x8d, 0x7d, 0xd1, 0x03, 0x28, 0x2a, 0xa1, 0x26, 0x34, 0xce, 0xae, 0x87, 0x57, 0x83, 0x0e,
	0xb6, 0xff, 0x42, 0x16, 0xd4, 0xba, 0x27, 0xc3, 0x6e, 0xc7, 0x36, 0x44, 0xbc, 0x3f, 0xec, 0xf5,
	0x4e, 0xf0, 0xad, 0x5d, 0x11, 0x9b, 0xe1, 0xd5, 0xe0, 0xf6, 0xa6, 0xf3, 0xde, 0xae, 0xa2, 0x35,
	0xb0, 0xce, 0x2f, 0xfa, 0x83, 0xeb, 0x2e, 0x3e, 0xe9, 0xd9, 0xe6, 0x29, 0x86, 0xd2, 0x1f, 0xcd,
	0xa7, 0xa3, 0x49, 0xc0, 0xa6, 0x7c, 0xec, 0xfa, 0x31, 0xdd, 0x2b, 0xb2, 0x7b, 0x2a, 0x3b, 0xa2,
	0xf1, 0x1d, 0x09, 0xf7, 0x26, 0xf1, 0xdb, 0x20, 0x1e, 0x15, 0xd9, 0x91, 0xca, 0xfe, 0x0a, 0x00,
	0x00, 0xff, 0xff, 0x99, 0x8c, 0x67, 0xfc, 0xca, 0x06, 0x00, 0x00,
}
